spring:
  datasource:
    username: test
    password: 1234
    url: jdbc:mysql://localhost/visited?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create

#server:
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-type: PKCS12
#    key-alias: spring
#    key-store-password: dhalstjd1